### ISSUE TITLE
Taking care of good mood in the team 

### ISSUE THREAD

**Issue by AndrzejLech** [carcassonne-team/Ice-Cream-Finder#6]
;) It is important to maintain good mood and good relations while programming.

**Comment by mikolajgawronski** [comment]
@AndrzejLech I think you did a really good job on maintaining good team relations. We had high spirits while our project was reviewed. Good job. Im closing the issue.

**Comment by Overnerfed** [comment]
@mikolajgawronski Nothing to add. 🥇
